server:
  port: 8080
eureka:
  instance:
    hostname: localhost
spring:
  application:
    name: eshop-gateway
  cloud:
    gateway:
      routes:
        - id: item-service
          uri: http://localhost:8081/
          predicates:
            - Path=/items/**
        - id: cart-service
          uri: http://localhost:8082/
          predicates:
            - Path=/cart/**
        - id: comment-service
          uri: http://localhost:8083/
          predicates:
            - Path=/comments/**