server:
  port: 8081
spring:
  application:
    name: item-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
eureka:
  instance:
    hostname: localhost
