server:
  port: 8082
spring:
  application:
    name: cart-service
  cloud:
    discovery:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/eshop
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  show-sql: true
eureka:
  instance:
    hostname: localhost
info:
  app:
    name: "this is cart-service"
    version: "0.0.1"
    description: "test 2"
management:
  endpoint:
    health:
      group:
        custom:
          include: diskSpace,ping
          show-components: always
          show-details: always
          status:
            http-mapping:
              up: 207
      prometheus:
        enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    env:
      enabled: true